const express = require("express")
const { protect } = require("../middleware/authMiddleware")
const { getProfile, updateProfile, uploadAvatar, deleteAvatar, changePassword } = require("../controllers/profileController")
const { uploadAvatar: multerAvatar } = require("../middleware/uploadAvatar")
const router = express.Router()
router.get("/",             protect, getProfile)
router.patch("/",           protect, updateProfile)
router.post("/avatar",      protect, multerAvatar, uploadAvatar)
router.delete("/avatar",    protect, deleteAvatar)
router.patch("/password",   protect, changePassword)
module.exports = router
