const { OAuth2Client } = require("google-auth-library");
const prisma = require("../lib/prisma");

const googleClientId = process.env.GOOGLE_CLIENT_ID || process.env.VITE_GOOGLE_CLIENT_ID;
const googleClientSecret = process.env.GOOGLE_CLIENT_SECRET;
const client = new OAuth2Client(googleClientId);

/* ════════════════════════════════════════════════════════════════════════
 * Legacy One-Tap path (kept for backwards compatibility)
 * ────────────────────────────────────────────────────────────────────────
 * `verifyGoogleToken` accepts an ID token forwarded from Google's One-Tap
 * SDK on the frontend. The new primary flow is OAuth redirect (see helpers
 * below) — it doesn't go through this function — but we keep it exported
 * so existing callers don't break during the transition.
 * ════════════════════════════════════════════════════════════════════════ */
async function verifyGoogleToken(credential) {
  if (!googleClientId) {
    throw new Error("GOOGLE_CLIENT_ID is not configured on the API server");
  }

  const ticket = await client.verifyIdToken({
    idToken: credential,
    audience: googleClientId,
  });

  const payload = ticket.getPayload();

  if (!payload) {
    throw new Error("Invalid Google token");
  }

  return {
    googleId: payload.sub,
    email: String(payload.email || "").toLowerCase(),
    fullName: payload.name,
    avatarUrl: payload.picture || null,
    emailVerified: payload.email_verified,
  };
}

/* ════════════════════════════════════════════════════════════════════════
 * OAuth Authorization Code redirect flow (PRIMARY)
 * ────────────────────────────────────────────────────────────────────────
 * Why this beats One-Tap:
 *   · No third-party cookies needed (the user authenticates on
 *     accounts.google.com which is first-party while they're there)
 *   · No "Access other apps" prompt in Brave Shields
 *   · No popup blockers
 *   · Works in Safari ITP, Firefox Strict, every browser default
 *   · Same UX as GitHub / Linear / Vercel / Notion
 *
 * Threat model · CSRF:
 *   The `state` parameter binds the auth flow to this user's session. We
 *   generate it in startGoogleOAuth, set it as an httpOnly cookie, then
 *   verify the cookie value matches the `state` query param when Google
 *   redirects back. If they don't match → reject the request. An attacker
 *   who lures the victim to a forged callback URL can't match this state.
 *
 * Threat model · token leak via Referer:
 *   We accept the OAuth code on the SERVER (server-side exchange) so the
 *   ID token and access token never enter the frontend. Only a short-
 *   lived JWT (our own session token) is handed to the SPA via URL
 *   fragment on the return-page redirect, which is invisible to servers
 *   (fragments aren't sent in the HTTP request line).
 * ════════════════════════════════════════════════════════════════════════ */

const REQUESTED_SCOPES = [
  "openid",
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/userinfo.profile",
];

/**
 * Build the Google authorization URL the browser will navigate to.
 *
 * @param {object}  args
 * @param {string}  args.state          — opaque CSRF token, generated by caller
 * @param {string}  args.nonce          — replay-resistance for the returned ID token
 * @param {string}  args.redirectUri    — exact match against Google Cloud Console
 * @param {string=} args.loginHint      — optional email pre-fill
 */
function buildAuthUrl({ state, nonce, redirectUri, loginHint }) {
  if (!googleClientId) {
    throw new Error("GOOGLE_CLIENT_ID is not configured on the API server");
  }
  if (!state || !nonce) {
    throw new Error("state and nonce are required");
  }

  // OAuth2Client.generateAuthUrl handles URL building + percent-encoding.
  // We pass `prompt=select_account` so users can pick which Google account
  // to use even if they're already signed in to one — important on shared
  // devices and for users with personal+work accounts.
  const localClient = new OAuth2Client(googleClientId, googleClientSecret, redirectUri);
  return localClient.generateAuthUrl({
    access_type:  "online",   // we don't need refresh tokens; ID token is enough
    scope:        REQUESTED_SCOPES,
    state,
    prompt:       "select_account",
    include_granted_scopes: true,
    login_hint:   loginHint || undefined,
    // OpenID Connect nonce — Google echoes this into the ID token so we
    // can detect replay attempts during exchange.
    // google-auth-library accepts arbitrary URL params via the second arg
    // shape, but generateAuthUrl coerces them; nonce goes in via params.
  }) + `&nonce=${encodeURIComponent(nonce)}`;
}

/**
 * Server-side code-for-token exchange. Returns the verified user profile
 * derived from the ID token in the exchange response. Never returns raw
 * tokens to the caller — they have no reason to leave this module.
 *
 * @param {object} args
 * @param {string} args.code         — the `code` query param Google sent us
 * @param {string} args.redirectUri  — MUST match the one used in buildAuthUrl
 * @param {string} args.expectedNonce — the nonce we generated on /start
 */
async function exchangeCodeForProfile({ code, redirectUri, expectedNonce }) {
  if (!googleClientId || !googleClientSecret) {
    throw new Error("GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET must both be set on the API server");
  }
  if (!code) {
    throw new Error("Missing OAuth code");
  }

  const localClient = new OAuth2Client(googleClientId, googleClientSecret, redirectUri);
  const { tokens } = await localClient.getToken(code);
  if (!tokens?.id_token) {
    throw new Error("Google did not return an ID token");
  }

  // Verify signature, audience, AND nonce. The nonce check is the
  // replay-protection layer — without it an attacker who intercepted
  // a code at any point could try to reuse it in their own session.
  const ticket = await localClient.verifyIdToken({
    idToken: tokens.id_token,
    audience: googleClientId,
  });
  const payload = ticket.getPayload();
  if (!payload) {
    throw new Error("Invalid Google ID token");
  }
  if (expectedNonce && payload.nonce !== expectedNonce) {
    throw new Error("ID token nonce mismatch — possible replay attack");
  }

  return {
    googleId:      payload.sub,
    email:         String(payload.email || "").toLowerCase(),
    fullName:      payload.name,
    avatarUrl:     payload.picture || null,
    emailVerified: payload.email_verified,
  };
}

async function findOrCreateGoogleUser(profile) {
  if (!profile.emailVerified) {
    throw new Error("Google email is not verified");
  }

  let user = await prisma.user.findUnique({ where: { email: profile.email } });

  if (user) {
    user = await prisma.user.update({
      where: { email: profile.email },
      data: {
        googleId: profile.googleId,
        avatarUrl: profile.avatarUrl,
        authProvider: "google",
        status: "active",
        lastLoginAt: new Date(),
      },
      include: { profile: true },
    });

    if (!user.profile) {
      await prisma.userProfile.create({ data: { userId: user.id } });
    }

    return user;
  }

  user = await prisma.user.create({
    data: {
      fullName: profile.fullName,
      email: profile.email,
      googleId: profile.googleId,
      avatarUrl: profile.avatarUrl,
      authProvider: "google",
      passwordHash: null,
      status: "active",
      lastLoginAt: new Date(),
      profile: { create: {} },
    },
  });

  return user;
}

module.exports = {
  verifyGoogleToken,
  findOrCreateGoogleUser,
  buildAuthUrl,
  exchangeCodeForProfile,
};
