import { useEffect, useRef, useState } from "react"
import { AnimatePresence, m, useReducedMotion } from "framer-motion"
import { useTranslation } from "react-i18next"
import Image from "../ui/Image"
import { Link } from "react-router-dom"
import {
  ArrowRight,
  ChevronDown,
  FileText,
  ExternalLink,
  Star,
  BadgeCheck,
  Settings2,
  Sparkles,
} from "lucide-react"
import KineticHeadline from "../motion/KineticHeadline"

import SocialLinks, { FOLLOW_SOCIALS } from "../SocialLinks"
import { buildApiUrl } from "../../lib/api"
import useProof from "../../hooks/useProof"

/* CVs — three professional profiles, generated by the API from the Bio CMS
 * rows (GET /api/v1/bio/cv.pdf?track=…&lang=…, see src/config/cvTracks.js).
 *
 * The dropdown picker below lists all three with a short subtitle so the
 * recruiter can pick the variant that matches their role. The static PDFs
 * under /public/cv/ stay in place as a fallback but are no longer linked. */
const cvUrl = (track, lang) =>
  buildApiUrl(`/api/v1/bio/cv.pdf?track=${encodeURIComponent(track)}&lang=${lang === "es" ? "es" : "en"}`)

const CV_OPTIONS = [
  {
    id: "fullstack",
    track: "fullstack",
    titleKey: "hero.cvs.fullstackTitle",
    titleFallback: "Full-Stack Software Engineer",
    subtitleKey: "hero.cvs.fullstackSubtitle",
    subtitleFallback: "Node · Django · React · Cloud",
  },
  {
    id: "ict-stem",
    track: "ict-stem",
    titleKey: "hero.cvs.ictStemTitle",
    titleFallback: "ICT Coordinator & STEM Instructor",
    subtitleKey: "hero.cvs.ictStemSubtitle",
    subtitleFallback: "Education · Curriculum · Infrastructure",
  },
  {
    id: "support",
    track: "support",
    titleKey: "hero.cvs.supportTitle",
    titleFallback: "Technical Support Engineer",
    subtitleKey: "hero.cvs.supportSubtitle",
    subtitleFallback: "IT operations · Networks · End-user support",
  },
]

/**
 * AboutHero · V3.2 — 3-column composition with full social row + CV download
 *
 * Layout:
 *   [Greeting + name + stats + CTAs + 6 socials]   [Portrait]   [Tagline + review + role + trust]
 *
 * Secondary CTA replaced: "Explore Store" → "Download my CV" (Spanish PDF).
 *
 * Brand tokens only (Royal Violet, Soft Terracotta, Charcoal, Mist).
 * Right column hidden below lg so mobile stays focused on the headline +
 * portrait. All idle motion respects `prefers-reduced-motion`.
 */

const profilePhoto = "/images/profile/Ukizuru_Mustapha_Photo.jpg"

/* ─────────────────────────── content ─────────────────────────────────── */

const TRUST_BULLETS = [
  { icon: BadgeCheck, label: "Proven Results", desc: "Delivered across schools & businesses" },
  { icon: Settings2, label: "Expert Systems", desc: "Infrastructure & digital platforms" },
  { icon: Sparkles, label: "STEM & EdTech", desc: "Coding, robotics, digital learning" },
]

const REVIEW_INITIALS = ["AM", "JN", "CK", "TM"]

const HERO_BG =
  "radial-gradient(at 100% 0%, rgb(var(--color-violet-rgb)/0.10) 0px, transparent 55%), " +
  "radial-gradient(at 0% 100%, rgb(var(--color-terracotta-rgb)/0.18) 0px, transparent 50%), " +
  "linear-gradient(160deg, var(--color-mist) 0%, var(--color-violet-pale) 40%, var(--color-slate-100) 100%)"

// Conic ring around the portrait. Middle stop uses Violet Light
// (var(--color-violet-light), brand v3 --u-violet-lt) instead of Tailwind's off-palette
// Tailwind violet-600 — keeps the brightness arc while staying in the sanctioned
// token system per Brand v3 §04 (no hex outside the five tiers).
const RING_GRADIENT =
  "conic-gradient(from 0deg, var(--color-terracotta) 0%, var(--color-violet) 35%, var(--color-violet-light) 50%, var(--color-violet) 65%, var(--color-terracotta) 100%)"

/* ─────────────────────────── component ───────────────────────────────── */

export default function AboutHero() {
  const { t } = useTranslation("about")
  /* Live proof numbers (GET /api/v1/bio/proof); static fallbacks while
   * loading, and a tile disappears when its DB value is 0. */
  const proof = useProof().data
  const years      = proof ? proof.years     : 8
  const projects   = proof ? proof.projects  : 10
  const rating     = proof ? proof.avgRating : 4.3
  const hasReviews = !proof || proof.reviews > 0
  const reduced = useReducedMotion()

  const stagger = {
    hidden: {},
    show: {
      transition: {
        staggerChildren: reduced ? 0 : 0.08,
        delayChildren: 0.1,
      },
    },
  }
  const fadeUp = {
    hidden: { opacity: 0, y: reduced ? 0 : 18 },
    show: { opacity: 1, y: 0, transition: { duration: 0.55, ease: [0.22, 1, 0.36, 1] } },
  }

  return (
    <section
      aria-labelledby="about-hero-title"
      className="relative min-h-[100dvh] overflow-hidden"
      style={{ background: HERO_BG }}
    >
      {/* Idle ring rotation + portrait float */}
      <style>{`
        @keyframes ukzAboutRing { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @keyframes ukzAboutFloat { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-6px); } }
        .ukz-about-ring { animation: ukzAboutRing 40s linear infinite; }
        .ukz-about-float { animation: ukzAboutFloat 6s ease-in-out infinite; }
        @media (prefers-reduced-motion: reduce) {
          .ukz-about-ring, .ukz-about-float { animation: none; }
        }
      `}</style>

      {/* Decorative blobs */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute right-0 top-0 h-[600px] w-[600px] rounded-full bg-violet/5 blur-3xl"
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute -bottom-20 -left-20 h-[400px] w-[400px] rounded-full bg-terracotta/15 blur-2xl"
      />

      <Container className="flex min-h-[100dvh] items-center py-12 sm:py-16 lg:py-20">
        <div className="grid w-full items-center gap-10 lg:grid-cols-[1fr_auto_1fr] lg:gap-0">

          {/* ═══ LEFT, greeting · stats · CTAs · socials ═══ */}
          <m.div
            variants={stagger}
            initial="hidden"
            animate="show"
            className="flex flex-col gap-7 pr-0 lg:pr-8"
          >
            {/* Greeting + headline */}
            <m.div variants={fadeUp} className="flex flex-col gap-2">
              <p className="text-[clamp(16px,1.4vw,20px)] font-semibold text-charcoal-80/65">
                {t("hero.helloIAm")}
              </p>
              {/* Phase 10b · kinetic word-by-word reveal. The legacy
                  decorative underline is dropped — the highlight tone
                  (terracotta) carries the same emphasis function and the
                  reveal motion supplies the visual interest the underline
                  was filling in for. */}
              <KineticHeadline
                as="h1"
                id="about-hero-title"
                className="text-display text-violet text-balance"
                stagger={0.08}
                parts={[
                  { text: "Mustapha" },
                  { text: "Ukizuru.", highlight: true },
                ]}
                highlightClassName="text-terracotta"
              />
            </m.div>

            {/* Stats */}
            {(years > 0 || projects > 0) && (
              <m.div variants={fadeUp} className="flex items-center gap-4">
                {years > 0 && (
                  <div>
                    <span className="text-[clamp(40px,5vw,52px)] font-extrabold leading-none text-violet tabular-nums">
                      {years}+
                    </span>
                    <div className="mt-1 text-[10.5px] font-bold uppercase tracking-[0.2em] text-charcoal-80/65">
                      {t("hero.yearsExperience")}
                    </div>
                  </div>
                )}
                {years > 0 && projects > 0 && (
                  <div aria-hidden="true" className="h-12 w-px bg-charcoal-80/15" />
                )}
                {projects > 0 && (
                  <div>
                    <span className="text-[clamp(28px,3.5vw,38px)] font-extrabold leading-none text-violet tabular-nums">
                      {projects}+
                    </span>
                    <div className="mt-1 text-[10.5px] font-bold uppercase tracking-[0.2em] text-charcoal-80/65">
                      {t("hero.projectsDelivered")}
                    </div>
                  </div>
                )}
              </m.div>
            )}

            {/* CTAs, primary: Book Consultation · secondary: Download CV */}
            <m.div variants={fadeUp} className="flex flex-wrap gap-3">
              {/* Primary conversion CTA — Innovation Gradient (Brand v3 sacred,
                  reserved for Book / Buy / Checkout / Contact CTAs). */}
              <Link
                to="/contact"
                className="group relative inline-flex items-center gap-2 overflow-hidden rounded-xl bg-grad-innovation px-6 py-3.5 text-[14px] font-bold !text-white shadow-[0_14px_34px_-8px_rgb(var(--color-violet-rgb)/0.55),0_4px_10px_-2px_rgb(var(--color-azure-rgb)/0.25)] ring-1 ring-inset ring-white/15 transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_20px_44px_-8px_rgb(var(--color-violet-rgb)/0.65),0_6px_14px_-2px_rgb(var(--color-azure-rgb)/0.32)] focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-azure/50 focus-visible:ring-offset-2"
              >
                <span
                  aria-hidden="true"
                  className="pointer-events-none absolute inset-x-0 top-0 h-1/2 bg-gradient-to-b from-white/20 to-transparent"
                />
                <span className="relative">{t("cta.letsTalk", "Contact")}</span>
                <ArrowRight
                  className="relative h-4 w-4 !text-white transition-transform duration-300 group-hover:translate-x-0.5"
                  aria-hidden="true"
                />
              </Link>

              <CvPicker t={t} />
            </m.div>

            {/* Socials — filled brand chips, no surrounding panel.
                Same SocialLinks component the Footer uses, rendered
                directly on the hero's mist surface. */}
            <m.div variants={fadeUp} className="flex flex-wrap items-center gap-3">
              <span className="text-[10.5px] font-bold uppercase tracking-[0.18em] text-charcoal-80/65">
                {t("hero.connectLabel")}
              </span>
              <div aria-hidden="true" className="h-px max-w-[40px] flex-1 bg-charcoal-80/15" />
              <SocialLinks
                platforms={FOLLOW_SOCIALS}
                variant="filled"
                size="sm"
                align="start"
                ariaLabel="Connect with Mustapha"
              />
            </m.div>
          </m.div>

          {/* ═══ CENTRE, circular portrait with rotating gradient ring ═══ */}
          <m.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1], delay: 0.1 }}
            className="relative mx-auto my-6 flex items-center justify-center lg:my-0"
            style={{ width: "min(340px, 85vw)", height: "min(400px, 100vw)" }}
          >
            {/* Rotating brand gradient ring */}
            <div
              aria-hidden="true"
              className="ukz-about-ring absolute inset-0 rounded-full"
              style={{ background: RING_GRADIENT }}
            />
            {/* Inner mist disc, leaves a 6 px gap so the ring shows through */}
            <div
              aria-hidden="true"
              className="absolute inset-[6px] rounded-full"
              style={{ background: "var(--color-mist)" }}
            />

            {/* Portrait, gentle idle float */}
            <div
              className="ukz-about-float relative z-10 overflow-hidden rounded-full shadow-[0_20px_60px_-10px_rgb(var(--color-violet-rgb)/0.30)]"
              style={{ width: "min(320px, 80vw)", height: "min(380px, 95vw)" }}
            >
              <Image
                src={profilePhoto}
                alt={t("hero.portraitAlt")}
                width={1080}
                height={1080}
                widths={[448, 1080]}
                sizes="(max-width: 640px) 80vw, 320px"
                loading="eager"
                fetchPriority="high"
                className="block h-full w-full"
                imgClassName="h-full w-full object-cover object-top"
              />
            </div>
          </m.div>

          {/* ═══ RIGHT, tagline · review · role · trust bullets (lg+ only) ═══ */}
          <m.div
            variants={stagger}
            initial="hidden"
            animate="show"
            className="hidden flex-col gap-7 pl-0 lg:flex lg:pl-8"
          >
            {/* Tagline */}
            <m.div variants={fadeUp} className="text-right">
              <p className="text-[clamp(15px,1.1vw,17px)] italic leading-7 text-charcoal-80/65">
                {t("hero.tagline1")}
                <br />
                <span className="font-semibold not-italic text-violet">
                  {t("hero.tagline2")}
                </span>
              </p>
            </m.div>

            {/* Review card */}
            {hasReviews && (
            <m.div variants={fadeUp} className="flex justify-end">
              <div className="rounded-xl border border-charcoal-80/10 bg-white px-5 py-4 shadow-[0_12px_32px_-8px_rgb(var(--color-violet-rgb)/0.15)]">
                <div className="flex items-center gap-3 text-[13px] font-semibold">
                  <span className="text-[12px] font-normal text-charcoal-80/65">
                    {t("hero.clientReviews")}
                  </span>
                  <div className="flex gap-0.5 text-terracotta">
                    {Array.from({ length: 5 }).map((_, i) => (
                      <Star key={i} className="h-3.5 w-3.5 fill-current" aria-hidden="true" />
                    ))}
                  </div>
                </div>
                <div className="mt-2.5 flex items-center gap-2.5">
                  <div className="flex -space-x-2">
                    {REVIEW_INITIALS.map((init) => (
                      <div
                        key={init}
                        className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-violet text-[9.5px] font-bold text-white"
                      >
                        {init}
                      </div>
                    ))}
                  </div>
                  <span className="text-[20px] font-extrabold text-violet tabular-nums">
                    {rating.toFixed(1)}
                  </span>
                </div>
                <div className="mt-1.5 text-[10px] text-charcoal-80/65">
                  {t("hero.basedOnFeedback")}
                </div>
              </div>
            </m.div>
            )}

            {/* Role */}
            <m.div variants={fadeUp} className="text-right">
              <p className="text-[12px] font-bold uppercase tracking-[0.18em] text-charcoal-80/65">
                {t("hero.technologyKicker")}
              </p>
              <p
                className="text-[clamp(28px,2.8vw,36px)] font-extrabold leading-tight tracking-tight text-violet"
                style={{ fontStyle: "italic" }}
              >
                {t("hero.consultantWord")}
              </p>
            </m.div>

            {/* Trust bullets */}
            <m.div variants={fadeUp} className="flex flex-col gap-3">
              {TRUST_BULLETS.map((bullet) => {
                const Icon = bullet.icon
                return (
                  <div
                    key={bullet.label}
                    className="group flex items-center gap-3 rounded-xl p-1 text-[13px] transition hover:bg-white/40"
                  >
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-pale text-violet ring-1 ring-violet/10 transition group-hover:bg-violet group-hover:text-white">
                      <Icon className="h-4 w-4" strokeWidth={2} aria-hidden="true" />
                    </div>
                    <div>
                      <div className="font-semibold text-violet">{bullet.label}</div>
                      <div className="text-[11px] text-charcoal-80/65">{bullet.desc}</div>
                    </div>
                  </div>
                )
              })}
            </m.div>
          </m.div>
        </div>
      </Container>
    </section>
  )
}

/* Local container — keeps the file self-contained so it can be imported
 * without depending on Home.jsx's internal Container helper. */
function Container({ children, className = "" }) {
  return (
    <div className={`mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 ${className}`}>
      {children}
    </div>
  )
}

/* CvPicker — "View My CVs" dropdown listing three professional profiles.
 *
 * Behaviour:
 *   • Opens on click, closes on outside-click / Escape / option click.
 *   • Each option opens its PDF in a new tab (target=_blank) so the
 *     visitor's place on AboutPage is preserved.
 *   • Keyboard-friendly: button has aria-expanded + aria-haspopup;
 *     menu items are real anchors so Tab navigation works out of the box.
 *   • Brand v3.1: violet ghost trigger, white menu with charcoal-80/8 ring,
 *     popover shadow, Innovation-gradient-free (this is a secondary CTA).
 */
function CvPicker({ t }) {
  const { i18n } = useTranslation("about")
  const [open, setOpen] = useState(false)
  // Viewport-aware flip: if the trigger is too close to the bottom edge,
  // open the menu UPWARD so the last item is never clipped. Estimated
  // menu height (header row + 3 items × ~62 px ≈ 220 px) + 16 px breathing
  // room. Cheap measurement done at open-time so we don't need a layout
  // observer or floating-ui dependency.
  const [placement, setPlacement] = useState("bottom")
  const rootRef = useRef(null)
  const triggerRef = useRef(null)

  // Click outside + Escape closes the menu.
  useEffect(() => {
    if (!open) return undefined
    function onPointer(e) {
      if (rootRef.current && !rootRef.current.contains(e.target)) setOpen(false)
    }
    function onKey(e) {
      if (e.key === "Escape") setOpen(false)
    }
    document.addEventListener("mousedown", onPointer)
    document.addEventListener("touchstart", onPointer)
    document.addEventListener("keydown", onKey)
    return () => {
      document.removeEventListener("mousedown", onPointer)
      document.removeEventListener("touchstart", onPointer)
      document.removeEventListener("keydown", onKey)
    }
  }, [open])

  // Decide bottom vs top placement the instant the menu opens. Reads the
  // trigger's getBoundingClientRect once — synchronous, sub-millisecond.
  // Re-evaluates on every open so the user can scroll, re-open, and get
  // the correct placement for the new viewport position.
  useEffect(() => {
    if (!open) return
    const trigger = triggerRef.current
    if (!trigger) return
    const rect = trigger.getBoundingClientRect()
    const spaceBelow = window.innerHeight - rect.bottom
    const MENU_HEIGHT_ESTIMATE = 240 // header row + 3 items + padding
    // eslint-disable-next-line react-hooks/set-state-in-effect -- placement depends on DOM measurement after open
    setPlacement(spaceBelow < MENU_HEIGHT_ESTIMATE + 16 ? "top" : "bottom")
  }, [open])

  return (
    <div ref={rootRef} className="relative">
      <button
        ref={triggerRef}
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-haspopup="menu"
        aria-expanded={open}
        className="group inline-flex items-center gap-2 rounded-xl border border-violet/25 bg-white/60 px-6 py-3.5 text-[14px] font-semibold text-violet transition hover:-translate-y-0.5 hover:bg-violet-pale focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-violet/30 focus-visible:ring-offset-2"
      >
        <FileText className="h-4 w-4 transition-transform group-hover:-translate-y-0.5" aria-hidden="true" />
        {t("hero.viewCvs", "View My CVs")}
        <ChevronDown
          className={`h-4 w-4 transition-transform duration-200 ${open ? "rotate-180" : ""}`}
          aria-hidden="true"
        />
      </button>

      <AnimatePresence>
        {open && (
          <m.div
            role="menu"
            aria-label={t("hero.cvs.menuLabel", "Professional profiles")}
            // Animate from a tiny offset in the direction the menu OPENS
            // FROM. Bottom-anchored menu slides down (y: -8 → 0); top-
            // anchored menu slides up (y: +8 → 0). The motion direction
            // reinforces the placement so users perceive it as a natural
            // expansion from the trigger, not a teleport.
            initial={{ opacity: 0, y: placement === "top" ? 8 : -8, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: placement === "top" ? 8 : -8, scale: 0.98 }}
            transition={{ duration: 0.16, ease: [0.22, 1, 0.36, 1] }}
            // Position relative to trigger; flip to `bottom-full + mb-2`
            // when there isn't room below. `max-h-[min(70vh,420px)]`
            // belt-and-suspenders cap: even if we mis-estimated height
            // for some translation, the menu never extends beyond 70%
            // of the viewport and the inner list scrolls. `overflow-y-auto`
            // moved INSIDE the <ul> so the rounded corners + header stay
            // intact while the menu body scrolls.
            className={[
              "absolute left-0 z-30 w-[min(20rem,90vw)] overflow-hidden rounded-xl border border-charcoal-80/8 bg-white shadow-[0_18px_44px_-12px_rgb(var(--color-violet-rgb)/0.28)]",
              "max-h-[min(70vh,420px)] flex flex-col",
              placement === "top" ? "bottom-full mb-2" : "top-full mt-2",
            ].join(" ")}
          >
            <div className="shrink-0 border-b border-charcoal-80/8 px-4 py-2.5">
              <p className="font-mono text-[10.5px] font-bold uppercase tracking-[0.16em] text-charcoal-80/65">
                {t("hero.cvs.menuLabel", "Professional profiles")}
              </p>
            </div>
            <ul className="flex-1 divide-y divide-charcoal-80/6 overflow-y-auto">
              {CV_OPTIONS.map((cv, idx) => (
                <li key={cv.id}>
                  <a
                    role="menuitem"
                    href={cvUrl(cv.track, i18n.language)}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={() => setOpen(false)}
                    className="group flex items-start gap-3 px-4 py-3 transition hover:bg-violet-pale focus-visible:outline-none focus-visible:bg-violet-pale"
                  >
                    <span className="mt-0.5 inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-violet/8 font-mono text-[11px] font-bold tabular-nums text-violet">
                      {idx + 1}
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-[13.5px] font-semibold text-charcoal">
                        {t(cv.titleKey, cv.titleFallback)}
                      </span>
                      <span className="block truncate text-[11.5px] text-charcoal-80/65">
                        {t(cv.subtitleKey, cv.subtitleFallback)}
                      </span>
                    </span>
                    <ExternalLink
                      className="mt-1 h-3.5 w-3.5 shrink-0 text-charcoal-80/40 transition group-hover:text-violet"
                      aria-hidden="true"
                    />
                  </a>
                </li>
              ))}
            </ul>
          </m.div>
        )}
      </AnimatePresence>
    </div>
  )
}
