import { useState } from "react"

/**
 * Image · SEO09 · responsive media primitive
 *
 * <picture> wrapper with WebP-first source + the original JPG/PNG fallback.
 * Enforces explicit width + height to eliminate CLS (Brand v3 § 16). Defaults
 * are SEO-friendly: lazy-load below-the-fold, async decoding, eager+high
 * priority for hero images.
 *
 *   <Image
 *     src="/images/hero.jpg"      // expects an adjacent /images/hero.webp
 *     alt="Mustapha at a school IT install in Mexico"
 *     width={1200} height={630}
 *     loading="eager" fetchPriority="high"   // for above-fold hero only
 *     sizes="(max-width: 768px) 100vw, 50vw"
 *   />
 *
 *   // Responsive variants generated by `npm run images:webp`
 *   // (/images/profile/x-112.webp, x-224.webp, x-448.webp):
 *   <Image src="/images/profile/x.jpg" widths={[112, 224, 448]} sizes="56px" ... />
 *
 * Props:
 *   src           — base path; webp counterpart auto-derived by extension swap
 *   alt           — REQUIRED for a11y + SEO. Empty string only for decorative
 *   width, height — REQUIRED in pixels (prevents CLS · Lighthouse penalises CLS > 0.1)
 *   loading       — "lazy" (default) or "eager"
 *   fetchPriority — "auto" (default) | "high" | "low"
 *   sizes         — responsive sizes attribute, defaults to "100vw"
 *   widths        — array of pixel widths; builds a WebP srcset from the
 *                   `<name>-<w>.webp` siblings emitted by scripts/convert-images.mjs
 *   srcSetWebp    — explicit WebP srcset override (takes precedence over `widths`)
 *   srcSetAvif    — explicit AVIF srcset override. AVIF siblings are written by
 *                   `node scripts/generate-avif.js --apply` (offline; the output
 *                   is committed). The AVIF <source> is emitted BEFORE the WebP
 *                   one because browsers pick the first type they support.
 *   srcSetJpg     — explicit fallback srcset override
 *   webp          — set false to skip the WebP <source> (e.g. runtime uploads
 *                   that have no generated sibling). Default true.
 *   className     — applied to the <picture> wrapper
 *   imgClassName  — applied to the inner <img>
 *   onError       — callback when neither source loads (allows fallback UI)
 *   ...rest       — forwarded to <img>
 *
 * Notes:
 * - When `src` is already absolute (http(s)://...) or has no .jpg/.png/.jpeg
 *   extension, the WebP <source> is omitted and the component degrades to a
 *   plain <img> in a <picture> wrapper.
 * - When the WebP variant is not yet generated, browsers will skip the
 *   <source> and fall back to the <img>. Run `npm run images:webp` (defined
 *   in web/package.json after SEO07) to generate WebP siblings.
 */
export function Image({
  src,
  alt,
  width,
  height,
  loading = "lazy",
  fetchPriority = "auto",
  sizes = "100vw",
  widths,
  srcSetWebp,
  srcSetAvif,
  srcSetJpg,
  webp = true,
  className = "",
  imgClassName = "",
  onError,
  ...rest
}) {
  const [errored, setErrored] = useState(false)

  if (import.meta.env?.DEV && !alt && alt !== "") {
    // Empty string is allowed (decorative); undefined is a developer mistake.
     
    console.warn("Image: `alt` prop is required for accessibility + SEO. Pass alt=\"\" only for decorative imagery.")
  }

  const isLocalRaster =
    webp &&
    typeof src === "string" &&
    /\.(jpe?g|png)$/i.test(src) &&
    !/^https?:\/\//i.test(src)

  const base    = isLocalRaster ? src.replace(/\.(jpe?g|png)$/i, "") : null
  const webpSrc = base ? `${base}.webp` : null
  const webpSet =
    srcSetWebp ||
    (base && Array.isArray(widths) && widths.length
      ? widths.map((w) => `${base}-${w}.webp ${w}w`).join(", ")
      : webpSrc)

  // AVIF, built from the same base and widths as the WebP set above.
  // scripts/generate-avif.js writes an .avif sibling for every responsive
  // .webp under public/images, so the two sets are always in step — and it
  // skips any image where AVIF came out larger, which is why this is a
  // progressive enhancement rather than a guarantee.
  //
  // Order matters: the browser takes the FIRST <source> whose type it
  // supports, so AVIF must precede WebP. Anything that understands neither
  // falls through to the original <img src>, exactly as before.
  const avifSrc = base ? `${base}.avif` : null
  const avifSet =
    srcSetAvif ||
    (base && Array.isArray(widths) && widths.length
      ? widths.map((w) => `${base}-${w}.avif ${w}w`).join(", ")
      : avifSrc)

  function handleError(e) {
    setErrored(true)
    if (typeof onError === "function") onError(e)
  }

  return (
    <picture className={className}>
      {!errored && avifSet && (
        <source srcSet={avifSet} type="image/avif" sizes={sizes} />
      )}
      {!errored && webpSet && (
        <source srcSet={webpSet} type="image/webp" sizes={sizes} />
      )}
      {!errored && srcSetJpg && (
        <source srcSet={srcSetJpg} sizes={sizes} />
      )}
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={loading}
        fetchPriority={fetchPriority}
        decoding="async"
        sizes={sizes}
        onError={handleError}
        className={imgClassName}
        {...rest}
      />
    </picture>
  )
}

export default Image
