const express = require("express")
const { protect, adminOnly } = require("../middleware/authMiddleware")
const { listMedia, deleteMedia, updateMedia, uploadMedia } = require("../controllers/adminMediaController")
const { uploadMedia: multerMedia } = require("../middleware/uploadAvatar")
const router = express.Router()
router.get("/",       protect, adminOnly, listMedia)
router.post("/",      protect, adminOnly, multerMedia, uploadMedia)
router.patch("/:id",  protect, adminOnly, updateMedia)
router.delete("/:id", protect, adminOnly, deleteMedia)
module.exports = router
