import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { HelmetProvider } from "react-helmet-async";

// I18N01 · initialise i18next BEFORE App so every component sees the
// language detection result on first paint.
import "./i18n"

import App from "./App";
import "./index.css";

import { ToastProvider } from "./context/ToastContext";
import { AuthProvider } from "./context/AuthContext";
import { CartProvider } from "./store/CartContext";
import { CompareProvider } from "./context/CompareContext"; // #3
import { NotificationProvider } from "./context/NotificationContext";
import OfflineBanner from "./components/OfflineBanner";
import SeoRouteManager from "./components/SeoRouteManager";
import SmoothScrollProvider from "./components/motion/SmoothScrollProvider";


// SEO10 · PWA · register the service worker generated by vite-plugin-pwa.
// `virtual:pwa-register` is provided by the plugin at build/dev time.
if (typeof window !== "undefined" && "serviceWorker" in navigator) {
  // Lazy import so the SPA still hydrates if the plugin isn't installed yet.
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      registerSW({
        immediate: true,
        onNeedRefresh() {
          // Soft-update: when a new SW is waiting, prompt the user via the
          // existing toast system. Reload skips the prompt for now to keep
          // the rollout simple; swap to a toast when CTA copy is finalized.
          if (typeof window !== "undefined") {
            // eslint-disable-next-line no-console
            console.info("[PWA] new content available, refresh to update");
          }
        },
        onOfflineReady() {
          // eslint-disable-next-line no-console
          console.info("[PWA] app ready to work offline");
        },
      });
    })
    .catch(() => {
      // vite-plugin-pwa not installed yet (e.g. fresh clone before npm install).
      // Silent fail — app continues to work without the SW.
    });
}

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <HelmetProvider>
      <BrowserRouter>
        <ToastProvider>
          <AuthProvider>
            <NotificationProvider>
              <CartProvider>
                <CompareProvider>
                  <SmoothScrollProvider>
                    <SeoRouteManager />
                    <App />
                    <OfflineBanner />
                  </SmoothScrollProvider>
                </CompareProvider>
              </CartProvider>
            </NotificationProvider>
          </AuthProvider>
        </ToastProvider>
      </BrowserRouter>
    </HelmetProvider>
  </React.StrictMode>,
);
